export class CreateAccountDto {
  companyName!: string;
  companyNameEn?: string;
  companyType?: string;
  industry?: string;
  businessDesc?: string;
  taxId?: string;
  branchCode?: string;
  branchName?: string;
  registeredCapital?: number;
  registrationDate?: string;
  registrationNo?: string;
  phone?: string;
  phone2?: string;
  fax?: string;
  email?: string;
  website?: string;
  lineOaId?: string;
  address?: string;
  subDistrict?: string;
  district?: string;
  province?: string;
  postalCode?: string;
  accountSource?: string;
  accountTier?: string;
  creditTerm?: number;
  creditLimit?: number;
  paymentMethod?: string;
  internalNotes?: string;
  customFields?: Record<string, unknown>;
}
